### ISSUE TITLE
L'interfaccia di backoffice si blocca al caricamento degli utenti di test

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#19]
Quando non sono stati caricati gli utenti di test, e si preme il bottone "Carica utenti di test" nell'interfaccia di backoffice, l'applicazione si blocca con lo spinner e non succede nulla. Dai log di WSO2 si vede che gli utenti vengono in realtà caricati.

Non so se sia collegato, ma dopo un po' WSO2 ha cominciato a loggare una gran quantità di questi errori fino a quando non ho ricaricato la pagina dal browser:

```
spid-testenv-identityserver    | [2017-12-20 15:20:25,473] ERROR {org.wso2.carbon.user.core.ldap.LDAPConnectionContext} -  Error obtaining connection. LDAP response read timed out, timeout used:5000ms.
spid-testenv-identityserver    | javax.naming.NamingException: LDAP response read timed out, timeout used:5000ms.
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.Connection.readReply(Connection.java:490)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:365)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2791)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
spid-testenv-identityserver    | 	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
spid-testenv-identityserver    | 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
spid-testenv-identityserver    | 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
spid-testenv-identityserver    | 	at javax.naming.InitialContext.init(InitialContext.java:244)
spid-testenv-identityserver    | 	at javax.naming.InitialContext.<init>(InitialContext.java:216)
spid-testenv-identityserver    | 	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.ldap.LDAPConnectionContext.getContext(LDAPConnectionContext.java:180)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager.getUserPropertyValues(ReadOnlyLDAPUserStoreManager.java:512)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserClaimValues(AbstractUserStoreManager.java:3269)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:632)
spid-testenv-identityserver    | 	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
spid-testenv-identityserver    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
spid-testenv-identityserver    | 	at java.lang.reflect.Method.invoke(Method.java:498)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:165)
spid-testenv-identityserver    | 	at java.security.AccessController.doPrivileged(Native Method)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:162)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:614)
spid-testenv-identityserver    | 	at org.wso2.carbon.identity.scim.common.listener.SCIMUserOperationListener.doPostAuthenticate(SCIMUserOperationListener.java:103)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.authenticateInternal(AbstractUserStoreManager.java:592)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$100(AbstractUserStoreManager.java:75)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$4.run(AbstractUserStoreManager.java:476)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$4.run(AbstractUserStoreManager.java:473)
spid-testenv-identityserver    | 	at java.security.AccessController.doPrivileged(Native Method)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.authenticate(AbstractUserStoreManager.java:473)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$3.run(AbstractUserStoreManager.java:461)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$3.run(AbstractUserStoreManager.java:452)
spid-testenv-identityserver    | 	at java.security.AccessController.doPrivileged(Native Method)
spid-testenv-identityserver    | 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.authenticate(AbstractUserStoreManager.java:452)
spid-testenv-identityserver    | 	at org.wso2.carbon.core.services.authentication.BasicAccessAuthenticator.doAuthentication(BasicAccessAuthenticator.java:182)
spid-testenv-identityserver    | 	at org.wso2.carbon.core.services.authentication.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:142)
spid-testenv-identityserver    | 	at org.wso2.carbon.server.admin.module.handler.AuthenticationHandler.isAuthenticated(AuthenticationHandler.java:180)
spid-testenv-identityserver    | 	at org.wso2.carbon.server.admin.module.handler.AuthenticationHandler.authenticate(AuthenticationHandler.java:105)
spid-testenv-identityserver    | 	at org.wso2.carbon.server.admin.module.handler.AuthenticationHandler.invoke(AuthenticationHandler.java:66)
spid-testenv-identityserver    | 	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
spid-testenv-identityserver    | 	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
spid-testenv-identityserver    | 	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
spid-testenv-identityserver    | 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
spid-testenv-identityserver    | 	at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
spid-testenv-identityserver    | 	at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:146)
spid-testenv-identityserver    | 	at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:231)
spid-testenv-identityserver    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
spid-testenv-identityserver    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
spid-testenv-identityserver    | 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
spid-testenv-identityserver    | 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
spid-testenv-identityserver    | 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
spid-testenv-identityserver    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
spid-testenv-identityserver    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
spid-testenv-identityserver    | 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
spid-testenv-identityserver    | 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
spid-testenv-identityserver    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
spid-testenv-identityserver    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
spid-testenv-identityserver    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
spid-testenv-identityserver    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
spid-testenv-identityserver    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
spid-testenv-identityserver    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
spid-testenv-identityserver    | 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:72)
spid-testenv-identityserver    | 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
spid-testenv-identityserver    | 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:60)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
spid-testenv-identityserver    | 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
spid-testenv-identityserver    | 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:958)
spid-testenv-identityserver    | 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
spid-testenv-identityserver    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
spid-testenv-identityserver    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
spid-testenv-identityserver    | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
spid-testenv-identityserver    | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
spid-testenv-identityserver    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)
spid-testenv-identityserver    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)
spid-testenv-identityserver    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
spid-testenv-identityserver    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
spid-testenv-identityserver    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
spid-testenv-identityserver    | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by damikael** [comment]
Si verifica ancora?

**Comment by mlocati** [comment]
Io ho provato ieri e tutto ha funzionato egregiamente

**Comment by damikael** [comment]
Perfetto, grazie @mlocati 
allora immagino si possa chiudere.
