### ISSUE TITLE
Don't crash when wso2 is not running

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv#21]
Whenever attempting to perform an operation while wso2 is not (yet) running the backoffice process crashes with the following error:

```
/Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/server/wso2/service-provider.js:179
			client.setSecurity(basicAuthSecurity);
			      ^

TypeError: Cannot read property 'setSecurity' of undefined
    at /Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/server/wso2/service-provider.js:179:10
    at /Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/node_modules/soap/lib/soap.js:59:5
    at /Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/node_modules/soap/lib/soap.js:23:18
    at /Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/node_modules/soap/lib/wsdl.js:2237:9
    at Request._callback (/Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/node_modules/soap/lib/http.js:114:14)
    at self.callback (/Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/al/Documents/git/TD/spid-testenv/spid-idp-backoffice/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

**Comment by alexrj** [comment]
(Otherwise when the docker is launched and user opens the backoffice before WSO2 has finished its initialization, backoffice will crash and the whole docker becomes unusable)

**Comment by damikael** [comment]
Fixed crash issue if WSO2 is not available
311e148c520d965f3dd5e0af19b0191fcde2fee7

Added a status led on the front end for checking when WSO2 is offline/online
761ba2de1a902108356a2010165efafe8f281dd1
