### ISSUE TITLE
Errore nel backoffice durante l'aggiunta di un SP: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mlocati** [italia/spid-testenv#40]
Ho compilato tutti i campi richiesti in https://spid-testenv-identityserver:8080 per l'aggiunta di un service provider.
Al salvataggio si verifica questo errore:

```
/spid-testenvironment/bo/backoffice/server/wso2/service-provider.js:316
    issuer: result.getApplicationResponse.return.inboundAuthenticationConfig.inboundAuthenticationRequestConfigs[0].inboundAuthKey
                                                                                                                ^

TypeError: Cannot read property '0' of undefined
    at /spid-testenvironment/bo/backoffice/server/wso2/service-provider.js:316:116
    at /spid-testenvironment/bo/backoffice/node_modules/soap/lib/client.js:182:7
    at finish (/spid-testenvironment/bo/backoffice/node_modules/soap/lib/client.js:394:14)
    at parseSync (/spid-testenvironment/bo/backoffice/node_modules/soap/lib/client.js:379:12)
    at /spid-testenvironment/bo/backoffice/node_modules/soap/lib/client.js:355:14
    at Request._callback (/spid-testenvironment/bo/backoffice/node_modules/soap/lib/http.js:117:5)
    at Request.self.callback (/spid-testenvironment/bo/backoffice/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/spid-testenvironment/bo/backoffice/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/spid-testenvironment/bo/backoffice/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

npm ERR! Linux 4.4.0-104-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start-prod"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-frontend-converted@0.1.0 start-prod: `node server/spid-idp-backoffice.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-frontend-converted@0.1.0 start-prod script 'node server/spid-idp-backoffice.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-frontend-converted package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/spid-idp-backoffice.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-frontend-converted
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-frontend-converted
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /spid-testenvironment/bo/backoffice/npm-debug.log

spid-testenv-backoffice exited with code 1
```

**Comment by mlocati** [comment]
Da notare che ho impostato un solo Assertion Consumer Service:

![acs](https://user-images.githubusercontent.com/928116/34985264-c95c32ec-fab3-11e7-8a77-1dfeeab928a1.png)

**Comment by damikael** [comment]
@mlocati puoi confermare che il problema non si presenta sull'ultima versione?

**Comment by mlocati** [comment]
Sì, confermo che con la versione 1.5 il problema non si ripresenta. Grazie!
